spring.application.name=BricksCompany
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-2

spring:
    data:
        dynamodb:
            entity2ddl:
                auto: create-only


